import logging
from enum import Enum

logger = logging.getLogger(__name__)


class BossNameEnum(Enum):
    """
    前端专用，可单独屏蔽部分未完全支持的boss，
    与src.core.boss.BossNameEnum一致
    """
    Dreamless = "无妄者"
    FallacyOfNoReturn = "无归的谬误"
    LampylumenMyriad = "辉萤军势"
    BellBorneGeochelone = "鸣钟之龟"
    InfernoRider = "燎照之骑"
    ImpermanenceHeron = "无常凶鹭"
    MechAbomination = "聚械机偶"
    MourningAix = "哀声鸷"
    ThunderingMephis = "朔雷之鳞"
    TempestMephis = "云闪之鳞"
    FeilianBeringal = "飞廉之猩"
    Crownless = "无冠者"
    Jue = "角"
    SentryConstruct = "异构武装"
    Hecate = "赫卡忒"
    Lorelei = "罗蕾莱"
    DragonOfDirge = "叹息古龙"
    NightmareFeilianBeringal = "梦魇飞廉之猩"
    NightmareImpermanenceHeron = "梦魇无常凶鹭"
    NightmareTempestMephis = "梦魇云闪之鳞"
    NightmareThunderingMephis = "梦魇朔雷之鳞"
    NightmareCrownless = "梦魇无冠者"
    NightmareInfernoRider = "梦魇燎照之骑"
    NightmareMourningAix = "梦魇哀声鸷"
    NightmareLampylumenMyriad = "梦魇辉萤军势"
    Fleurdelys = "芙露德莉斯"
    NightmareKelpie = "梦魇凯尔匹"
    LionessOfGlory = "荣耀狮像"
    NightmareHecate = "梦魇赫卡忒"
    Fenrico = "芬莱克"
    LadyOfTheSea = "海之女"
    TheFalseSovereign = "伪作的神王"
    ThrenodianLeviathan = "鸣式利维亚坦"
    Hyvatia = "海维夏"
    ReactorHusk = "炉芯机骸"
    Sigillum = "辛吉勒姆"
    NamelessExplorer = "无铭探索者"
    # SeedOfIllusoryOrigin = "虚妄诞生之种（限时提前开放）"
    Denia = "达妮娅"
    # NightmareAdamSmasherLimitedTime = "梦魇亚当·重锤（限时提前开放）"
    NightmareAdamSmasher = "梦魇亚当·重锤"
    # MyriadSnareRustfireChassisLimitedTime = "万囮牢·朽躯（限时提前开放）"
    MyriadSnareRustfireChassis = "万囮牢·朽躯"
    # CourtOfShackledSouls = "失坠困咎之庭（限时提前开放）"
    ThousandPuppetPavilion = "千傀重楼"
    CalamityEffigy = "天傀劫煞"
