# 脚本基础配置
AppPath: # 游戏路径，默认留空，从注册表读取游戏运行目录，为最后一个安装的游戏，若安装了多个版本的游戏，需指定具体版本，则需填上游戏路径，
           # 路径使用"\\"而不是"\" , 若无法读取注册表，且此值为空时无法在崩溃时自动重启游戏。
           # 例：AppPath: D:\\Wuthering Waves\\Wuthering Waves Game\\Wuthering Waves.exe
ModelName: "yolo" # 默认无需设置，已实现自动匹配声骸模型
OcrInterval: 0 # OCR识别间隔时间
GameMonitorTime: 5 # 游戏窗口检测间隔时间
LogFilePath: # 日志保存路径，留空即为项目根目录，如需设置，则需为"c:\\mc_log.txt"格式，使用"\\"而不是"\"

# 游戏崩溃捕获及处理
RestartWutheringWaves: false # 定时重启游戏，默认关闭
RestartWutheringWavesTime: 7200 # 时间单位为秒，仅当RestartWutheringWaves为true时生效

# 控制台信息
EchoDebugMode: true #声骸锁定功能DEBUG显示输出的开关
EchoSynthesisDebugMode: true # 声骸合成锁定功能DEBUG显示输出的开关

# 自动战斗及声骸锁定配置
MaxFightTime: 120 # 单次战斗最大时间 超过时间会进行下一个目标
MaxIdleTime: 12 # 战斗完成后的空闲时间，不能小于5
MaxSearchEchoesTime: 18 # 战斗完成后搜索声骸的最大时间，与MaxIdleTime/2 取较大值
SelectRoleInterval: 2 # 选择角色的时间间隔 最小为2 避免无法选择角色
DungeonWeeklyBossLevel: 40 # 自己可以掉落的周本(副本)boss最低等级（当前索拉等级*10）
CharacterHeal: true #是否判断角色是否阵亡 若阵亡则返回神像复活，请确保背包里面至少有一个复活药剂
SearchEchoes: true # 是否搜索声骸
SearchDreamlessEchoes: true # 是否搜索无妄者声骸
EchoLock: true #是否启用声骸锁定功能
EchoMaxContinuousLockQuantity: 25 # 最大连续检测到已锁定声骸的数量，超过此数量就停止

# 战斗策略
FightTactics: # 三个角色的释放技能顺序, 逗号分隔, e,q,r为技能, l(小写L)为向后闪避, a为普攻(默认连点0.3秒), 数字为间隔时间,a~0.5为普攻按下0.5秒,a(0.5)为连续普攻0.5秒，摩托车短按请用q~0.1
    - "q~0.1,e~0.1,a" # 守岸人
    #- "r,e,q~0.1,s,a(0.1),a" # 维里奈
    - "r,q~0.1,e,a,a,a,a~,e" # 长离
    - "q~0.1,e,r,e,a,a,a,a,a,e,a,a,a,a,a,e" # 今汐
# 战斗顺序，推荐奶妈起手
FightOrder: [1, 2, 3] # 123为角色在编队中的位置，改成321可使3号位维里奈先连招，上方战斗策略也需要对应将维里奈连招放到第一行

# 目标BOSS v1.0 boss都不需要插借位信标，需在2.0版本后手打一次解锁附近传送，剧情里打的不算
# 目标BOSS v2.0 boss都不需要插借位信标，需在2.0版本后手打一次解锁附近传送，剧情里打的不算
# 删除想打的boss前的井号，不打的加上井号，每行前面四个4个空格多一个少一个都不行，无特殊要求建议单刷无妄者
TargetBoss:
    # =========== v1.0 boss ===========
    - "无妄者"
    #- "无归的谬误"
    #- "辉萤军势"
    #- "鸣钟之龟"
    #- "燎照之骑"
    #- "无常凶鹭"
    #- "聚械机偶"
    #- "哀声鸷"
    #- "朔雷之鳞"
    #- "云闪之鳞"
    #- "飞廉之猩"
    #- "无冠者"
    #- "角"
    # =========== v2.0 boss ===========
    #- "异构武装"
    #- "赫卡忒"
    #- "罗蕾莱"
    #- "叹息古龙"
    #- "梦魇飞廉之猩"
    #- "梦魇无常凶鹭"
    #- "梦魇云闪之鳞"
    #- "梦魇朔雷之鳞"
    #- "梦魇无冠者"
    #- "梦魇燎照之骑"
    #- "梦魇哀声鸷"